version: '3.9'

services:
  proxy:
    networks:
      - ext_net
      - proxy_net
    volumes:
      - ./bind-mount/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1      
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  web:
    networks:
      - proxy_net
      - int_net
    volumes:
      - webdata:/usr/src/myapp      
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy: 
        condition: on-failure

  pma:
    networks:
      - proxy_net
      - int_net
    links: 
      - mysql
    secrets:
      - mysql_root_pass
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD_FILE: /run/secrets/mysql_root_pass
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  mysql:
    networks:
      - int_net
    secrets:
      - mysql_root_pass
      - mysql_database
      - mysql_user  
      - mysql_user_pass     
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_pass
    volumes:
      - mysqldata:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy: 
        condition: on-failure        

volumes:      
  mysqldata:
  webdata:

networks:
  ext_net:
    driver: overlay
  proxy_net:      
    driver: overlay
  int_net:
    driver: overlay

secrets:
  mysql_root_pass:
    file: ./secrets/mysql_root_pass.txt
  mysql_database:
    file: ./secrets/mysql_database.txt
  mysql_user:
    file: ./secrets/mysql_user.txt
  mysql_user_pass:
    file: ./secrets/mysql_user_pass.txt

